# Generated by Django 4.1.2 on 2022-10-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_discount_price_product_discountprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountprice',
            new_name='originalprice',
        ),
    ]
