# Generated by Django 4.1.2 on 2022-11-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_discountprice_product_originalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.IntegerField(default=15),
        ),
    ]
